# 9-dars

In [49]:
import pandas as pd

In [50]:
df=pd.read_csv('movies_initial.csv')

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   rating       24629 non-null  object
 4   runtime      43377 non-null  object
 5   genre        45615 non-null  object
 6   released     43002 non-null  object
 7   director     45409 non-null  object
 8   writer       42942 non-null  object
 9   cast         44928 non-null  object
 10  metacritic   9401 non-null   float64
 11  imdbRating   44300 non-null  float64
 12  imdbVotes    44299 non-null  float64
 13  poster       35798 non-null  object
 14  plot         42161 non-null  object
 15  fullplot     41421 non-null  object
 16  language     44899 non-null  object
 17  country      45830 non-null  object
 18  awards       23542 non-null  object
 19  lastupdated  46014 non-null  object
 20  type         45976 non-null  object
dtypes: float64(3), int64(1), object(17)
memory usage: 7.4+ MB

In [52]:
df.isnull().sum()

imdbID             0
title              0
year               0
rating         21385
runtime         2637
genre            399
released        3012
director         605
writer          3072
cast            1086
metacritic     36613
imdbRating      1714
imdbVotes       1715
poster         10216
plot            3853
fullplot        4593
language        1115
country          184
awards         22472
lastupdated        0
type              38
dtype: int64

In [53]:
for col in df.columns:
    if df[col].isnull().sum() > 10000:
        # 1) Agar NaN soni 10000 dan ko'p bo'lsa, ustunni o'chirish
        df.drop(columns=[col], inplace=True)
    elif df[col].dtype == 'object':
        # 2) Agar ustun turi object bo‘lsa va NaN soni 10 dan ko‘p bo‘lsa
        if df[col].isnull().sum() > 10:
            df[col].fillna(df[col].mode().iloc[0], inplace=True)
    else:
        # 3) Aks holda (sonli ustunlarda) NaN qiymatlarni o'rtacha bilan to'ldirish
        df[col].fillna(df[col].mean(), inplace=True)

C:\Users\aaa\AppData\Local\Temp\ipykernel_27888\2568463412.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_27888\2568463412.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode().iloc[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_27888\2568463412.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_27888\2568463412.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode().iloc[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_27888\2568463412.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode().iloc[0], inplace=True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  object
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   writer       46014 non-null  object
 8   cast         46014 non-null  object
 9   imdbRating   46014 non-null  float64
 10  imdbVotes    46014 non-null  float64
 11  plot         46014 non-null  object
 12  fullplot     46014 non-null  object
 13  language     46014 non-null  object
 14  country      46014 non-null  object
 15  lastupdated  46014 non-null  object
 16  type         46014 non-null  object
dtypes: float64(2), int64(1), object(14)
memory usage: 6.0+ MB

In [55]:
df.head(20)

,imdbID,title,year,runtime,genre,released,director,writer,cast,imdbRating,imdbVotes,plot,fullplot,language,country,lastupdated,type
0,1,Carmencita,1894,1 min,"Documentary, Short",2015-09-01,William K.L. Dickson,Woody Allen,Carmencita,5.9,1032.0,Performing on what looks like a small wooden s...,Performing on what looks like a small wooden s...,English,USA,2015-08-26 00:03:45.040000000,movie
1,5,Blacksmith Scene,1893,1 min,Short,1893-05-09,William K.L. Dickson,Woody Allen,"Charles Kayser, John Ott",6.2,1189.0,Three men hammer on an anvil and pass a bottle...,A stationary camera looks at a large anvil wit...,English,USA,2015-08-26 00:03:50.133000000,movie
2,3,Pauvre Pierrot,1892,4 min,"Animation, Comedy, Short",1892-10-28,�mile Reynaud,Woody Allen,Georges M�li�s,6.7,566.0,"One night, Arlequin come to see his lover Colo...","One night, Arlequin come to see his lover Colo...",English,France,2015-08-12 00:06:02.720000000,movie
3,8,Edison Kinetoscopic Record of a Sneeze,1894,1 min,"Documentary, Short",1894-01-09,William K.L. Dickson,Woody Allen,Fred Ott,5.9,988.0,A man (Thomas Edison's assistant) takes a pinc...,A man (Edison's assistant) takes a pinch of sn...,English,USA,2015-08-10 00:21:07.127000000,movie
4,10,Employees Leaving the Lumi�re Factory,1895,1 min,"Documentary, Short",1895-03-22,Louis Lumi�re,Woody Allen,Georges M�li�s,6.9,3469.0,A man opens the big gates to the Lumi�re facto...,A man opens the big gates to the Lumi�re facto...,English,France,2015-08-26 00:03:56.603000000,movie
5,12,The Arrival of a Train,1896,1 min,"Documentary, Short",1896-01-01,"Auguste Lumi�re, Louis Lumi�re",Woody Allen,Georges M�li�s,7.3,5043.0,A group of people are standing in a straight l...,A group of people are standing in a straight l...,English,France,2015-08-15 00:02:53.443000000,movie
6,14,Tables Turned on the Gardener,1895,1 min,"Comedy, Short",2015-09-01,Louis Lumi�re,Woody Allen,"Fran�ois Clerc, Beno�t Duval",7.1,2554.0,"A gardener is watering his flowers, when a mis...","A gardener is watering his flowers, when a mis...",English,France,2015-08-12 00:06:18.237000000,movie
7,29,Baby's Dinner,1895,1 min,"Documentary, Short",1895-12-28,Louis Lumi�re,Woody Allen,"Mrs. Auguste Lumiere, Andr�e Lumi�re, Auguste ...",5.9,1669.0,A baby is seated at a table between its cheerf...,A baby is seated at a table between its cheerf...,English,France,2015-08-12 00:06:40.657000000,movie
8,23,The Sea,1895,1 min,"Documentary, Short",1896-06-28,Louis Lumi�re,Woody Allen,Georges M�li�s,5.5,599.0,"Several little boys run along a pier, then jum...",The sea is before us. Some rocks are visible t...,English,France,2015-08-12 00:06:30.297000000,movie
9,70,D�molition d'un mur,1896,1 min,"Documentary, Short",2005-04-15,Louis Lumi�re,Woody Allen,Auguste Lumi�re,6.4,1359.0,Auguste Lumi�re directs four workers in the de...,Auguste Lumi�re directs four workers in the de...,English,France,2015-08-26 00:05:47.977000000,movie
10,91,The House of the Devil,1896,3 min,"Short, Horror",2015-09-01,Georges M�li�s,Georges M�li�s,"Jeanne d'Alcy, Georges M�li�s",6.8,1135.0,A bat flies into an ancient castle and transfo...,A bat flies into an ancient castle and transfo...,English,France,2015-08-26 00:06:16.697000000,movie
11,75,The Conjuring of a Woman at the House of Rober...,1896,1 min,Short,2015-09-01,Georges M�li�s,Woody Allen,"Jeanne d'Alcy, Georges M�li�s",6.3,759.0,A woman disappears on stage.,An elegantly dressed man enters through a stag...,English,France,2015-08-26 00:05:55.493000000,movie
12,131,A Terrible Night,1896,1 min,"Short, Comedy",2015-09-01,Georges M�li�s,Woody Allen,Georges M�li�s,5.9,498.0,"A man tries to get a good night's sleep, but i...","A man tries to get a good night's sleep, but i...",English,France,2015-08-26 00:07:48.213000000,movie
13,132,Une partie de cartes,1896,1 min,"Short, Biography",2015-09-01,Georges M�li�s,Georges M�li�s,"Gaston M�li�s, Georges M�li�s, Georgette M�li�s",5.1,462.0,Three friends are playing cards in a beer gard...,Three friends are playing cards in a beer gard...,English,France,2015-07-27 00:27:37.370000000,movie
14,138,The Bewitched Inn,1897,2 min,"Short, Comedy",2015-09-01,Georges M�li�s,Georges M�li�s,Georges M�li�s,6.5,329.0,A weary traveler stops at an inn along the way...,A weary traveler stops at an inn along the way...,English,France,2015-08-29 00:17:59.703000000,movie
15,192,"Ella Lola, a la Trilby",1898,90 min,Short,2015-09-01,James H. White,George L. Du Maurier (novel),Ella Lola,4.7,83.0,Dancer Ella Lola dances a routine based on the...,Dancer Ella Lola dances a routine based on the...,English,USA,2015-08-29 00:19:44.140000000,movie
16,211,A Trip to the Moon,1898,3 min,"Short, Fantasy",2015-09-01,Georges M�li�s,Georges M�li�s (creator),Georges M�li�s,7.6,1057.0,"""In the opening of this film is seen the astro...","""In the opening of this film is seen the astro...",English,France,2015-08-29 00:20:20.280000000,movie
17,230,Cinderella,1899,6 min,"Drama, Short",1899-12-25,Georges M�li�s,Charles Perrault (story),"Barral, Bleuette Bernon, Carmely, Jeanne d'Alcy",6.6,586.0,A fairy godmother magically turns Cinderella's...,A fairy godmother magically turns Cinderella's...,English,France,2015-08-29 00:20:56.217000000,movie
18,242,The Sign of the Cross,1899,3 min,"Short, Fantasy",1900-06-30,Georges M�li�s,Georges M�li�s,Georges M�li�s,6.3,388.0,The plot is unknown at this time.,Plot is unknown.,English,France,2015-08-29 00:21:15.827000000,movie
19,246,A Turn of the Century Illusionist,1899,1 min,Short,2015-09-01,Georges M�li�s,Woody Allen,Georges M�li�s,6.6,580.0,The plot is unknown at this time.,Plot is unknown.,English,France,2015-08-29 00:21:21.547000000,movie

<!-- # One hot encoding -->

In [56]:
df['type'].nunique()

2

In [57]:
df=pd.get_dummies(df,columns=['type'],prefix='type',dtype=int)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  object
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   writer       46014 non-null  object
 8   cast         46014 non-null  object
 9   imdbRating   46014 non-null  float64
 10  imdbVotes    46014 non-null  float64
 11  plot         46014 non-null  object
 12  fullplot     46014 non-null  object
 13  language     46014 non-null  object
 14  country      46014 non-null  object
 15  lastupdated  46014 non-null  object
 16  type_movie   46014 non-null  int64
 17  type_series  46014 non-null  int64
dtypes: float64(2), int64(3), object(13)
memory usage: 6.3+ MB

In [59]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [60]:
df['runtime']=encoder.fit_transform(df['runtime'])

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  int64
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   writer       46014 non-null  object
 8   cast         46014 non-null  object
 9   imdbRating   46014 non-null  float64
 10  imdbVotes    46014 non-null  float64
 11  plot         46014 non-null  object
 12  fullplot     46014 non-null  object
 13  language     46014 non-null  object
 14  country      46014 non-null  object
 15  lastupdated  46014 non-null  object
 16  type_movie   46014 non-null  int64
 17  type_series  46014 non-null  int64
dtypes: float64(2), int64(4), object(12)
memory usage: 6.3+ MB

# Frequency encoding

In [62]:
df['writer'].value_counts()

writer
Woody Allen                                                   3113
Werner Herzog                                                   32
Ingmar Bergman                                                  31
William Shakespeare (play)                                      25
Ki-duk Kim                                                      22
                                                              ...
Xiaolu Xue                                                       1
Esther Wouda                                                     1
Mary Shelley (novel), J. Searle Dawley                           1
Urban Gad                                                        1
Charles Foley (novel), Andr� de Lorde (play), Mack Sennett       1
Name: count, Length: 36500, dtype: int64

In [63]:
df['writer_freq']=df['writer'].map(df['writer'].value_counts())

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  int64
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   writer       46014 non-null  object
 8   cast         46014 non-null  object
 9   imdbRating   46014 non-null  float64
 10  imdbVotes    46014 non-null  float64
 11  plot         46014 non-null  object
 12  fullplot     46014 non-null  object
 13  language     46014 non-null  object
 14  country      46014 non-null  object
 15  lastupdated  46014 non-null  object
 16  type_movie   46014 non-null  int64
 17  type_series  46014 non-null  int64
 18  writer_freq  46014 non-null  int64
dtypes: float64(2), int64(5), object(12)
memory usage: 6.7+ MB

In [65]:
df.drop('writer', axis=1, inplace=True)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  int64
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   cast         46014 non-null  object
 8   imdbRating   46014 non-null  float64
 9   imdbVotes    46014 non-null  float64
 10  plot         46014 non-null  object
 11  fullplot     46014 non-null  object
 12  language     46014 non-null  object
 13  country      46014 non-null  object
 14  lastupdated  46014 non-null  object
 15  type_movie   46014 non-null  int64
 16  type_series  46014 non-null  int64
 17  writer_freq  46014 non-null  int64
dtypes: float64(2), int64(5), object(11)
memory usage: 6.3+ MB

In [67]:
df['year'].value_counts()

year
2015         2088
2014         2078
2013         1927
2012         1817
2011         1706
             ...
1887            1
1982�1986       1
1874            1
2018            1
2019            1
Name: count, Length: 170, dtype: int64

# Target encoding

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdbID       46014 non-null  int64
 1   title        46014 non-null  object
 2   year         46014 non-null  object
 3   runtime      46014 non-null  int64
 4   genre        46014 non-null  object
 5   released     46014 non-null  object
 6   director     46014 non-null  object
 7   cast         46014 non-null  object
 8   imdbRating   46014 non-null  float64
 9   imdbVotes    46014 non-null  float64
 10  plot         46014 non-null  object
 11  fullplot     46014 non-null  object
 12  language     46014 non-null  object
 13  country      46014 non-null  object
 14  lastupdated  46014 non-null  object
 15  type_movie   46014 non-null  int64
 16  type_series  46014 non-null  int64
 17  writer_freq  46014 non-null  int64
dtypes: float64(2), int64(5), object(11)
memory usage: 6.3+ MB

In [69]:
target_encoding = df.groupby('genre')['imdbRating'].mean()
df['genre_target'] = df['genre'].map(target_encoding)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   imdbID        46014 non-null  int64
 1   title         46014 non-null  object
 2   year          46014 non-null  object
 3   runtime       46014 non-null  int64
 4   genre         46014 non-null  object
 5   released      46014 non-null  object
 6   director      46014 non-null  object
 7   cast          46014 non-null  object
 8   imdbRating    46014 non-null  float64
 9   imdbVotes     46014 non-null  float64
 10  plot          46014 non-null  object
 11  fullplot      46014 non-null  object
 12  language      46014 non-null  object
 13  country       46014 non-null  object
 14  lastupdated   46014 non-null  object
 15  type_movie    46014 non-null  int64
 16  type_series   46014 non-null  int64
 17  writer_freq   46014 non-null  int64
 18  genre_target  46014 non-null  float64
dtypes: float64(3), int64(5), object(11)
memory usage: 6.7+ MB

In [71]:
df.drop('genre', axis=1, inplace=True)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   imdbID        46014 non-null  int64
 1   title         46014 non-null  object
 2   year          46014 non-null  object
 3   runtime       46014 non-null  int64
 4   released      46014 non-null  object
 5   director      46014 non-null  object
 6   cast          46014 non-null  object
 7   imdbRating    46014 non-null  float64
 8   imdbVotes     46014 non-null  float64
 9   plot          46014 non-null  object
 10  fullplot      46014 non-null  object
 11  language      46014 non-null  object
 12  country       46014 non-null  object
 13  lastupdated   46014 non-null  object
 14  type_movie    46014 non-null  int64
 15  type_series   46014 non-null  int64
 16  writer_freq   46014 non-null  int64
 17  genre_target  46014 non-null  float64
dtypes: float64(3), int64(5), object(10)
memory usage: 6.3+ MB

# Ordinal encoding

In [73]:
year_mapping=df['year'].value_counts()

In [77]:
df['year_ordinal']=df['year'].map(year_mapping)
df.drop('year', axis=1, inplace=True)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   imdbID        46014 non-null  int64
 1   title         46014 non-null  object
 2   runtime       46014 non-null  int64
 3   released      46014 non-null  object
 4   director      46014 non-null  object
 5   cast          46014 non-null  object
 6   imdbRating    46014 non-null  float64
 7   imdbVotes     46014 non-null  float64
 8   plot          46014 non-null  object
 9   fullplot      46014 non-null  object
 10  language      46014 non-null  object
 11  country       46014 non-null  object
 12  lastupdated   46014 non-null  object
 13  type_movie    46014 non-null  int64
 14  type_series   46014 non-null  int64
 15  writer_freq   46014 non-null  int64
 16  genre_target  46014 non-null  float64
 17  year_ordinal  46014 non-null  int64
dtypes: float64(3), int64(6), object(9)
memory usage: 6.3+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [82]:
def encode_qil(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            encoder = LabelEncoder()
            df[col] = encoder.fit_transform(df[col].astype(str))
    return df

In [83]:
encode_qil(df)

,imdbID,title,runtime,released,director,cast,imdbRating,imdbVotes,plot,fullplot,language,country,lastupdated,type_movie,type_series,writer_freq,genre_target,year_ordinal
0,1,6148,17,15527,18404,5910,5.900000,1032.000000,28745,27514,249,2469,24292,1,0,3113,6.654848,15
1,5,4756,17,1,18404,6491,6.200000,1189.000000,36242,5759,249,2469,24295,1,0,3113,6.346365,1
2,3,23646,262,0,18854,13778,6.700000,566.000000,28375,27018,249,663,12289,1,0,3113,7.410000,3
3,8,10011,17,2,18404,13001,5.900000,988.000000,6093,3946,249,2469,11495,1,0,3113,6.654848,15
4,10,10303,17,4,10847,13778,6.900000,3469.000000,6303,4058,249,663,24296,1,0,3113,6.654848,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46009,5005684,34752,348,15563,1474,38391,6.381454,11800.552134,34102,27729,1682,1260,38563,1,0,3113,6.685261,2088
46010,5013056,39098,348,15719,3045,13778,6.381454,11800.552134,28911,27726,249,2786,39240,1,0,1,5.078377,42
46011,5013980,8985,348,15527,13289,22530,6.381454,11800.552134,34102,27729,1490,1005,40225,1,0,2,7.034536,519
46012,5016760,34580,348,15531,8720,14482,6.381454,11800.552134,21988,18093,249,1671,40122,1,0,1,6.689445,2088
46013,5023260,33826,348,15527,11519,1603,6.381454,11800.552134,34102,27729,249,2469,43267,1,0,3113,6.066389,519

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46014 entries, 0 to 46013
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   imdbID        46014 non-null  int64
 1   title         46014 non-null  int64
 2   runtime       46014 non-null  int64
 3   released      46014 non-null  int64
 4   director      46014 non-null  int64
 5   cast          46014 non-null  int64
 6   imdbRating    46014 non-null  float64
 7   imdbVotes     46014 non-null  float64
 8   plot          46014 non-null  int64
 9   fullplot      46014 non-null  int64
 10  language      46014 non-null  int64
 11  country       46014 non-null  int64
 12  lastupdated   46014 non-null  int64
 13  type_movie    46014 non-null  int64
 14  type_series   46014 non-null  int64
 15  writer_freq   46014 non-null  int64
 16  genre_target  46014 non-null  float64
 17  year_ordinal  46014 non-null  int64
dtypes: float64(3), int64(15)
memory usage: 6.3 MB