# Vazifa
# 1-Kaggledan 1 ta dataset topish va dataprocessing 1-bo'lim amallarini bajarish

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('airports.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6393 entries, 0 to 6392
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AirportName         6393 non-null   object
 1   IATA                6373 non-null   object
 2   ICAO                5091 non-null   object
 3   TimeZone            6305 non-null   object
 4   City_Name           6393 non-null   object
 5   City_IATA           6331 non-null   object
 6   UTC_Offset_Hours    6305 non-null   float64
 7   UTC_Offset_Seconds  6305 non-null   float64
 8   Country_CodeA2      6379 non-null   object
 9   Country_CodeA3      6393 non-null   object
 10  Country_Name        6393 non-null   object
 11  GeoPointLat         6393 non-null   float64
 12  GeoPointLong        6393 non-null   float64
dtypes: float64(4), object(9)
memory usage: 649.4+ KB

In [7]:
df.head()

,AirportName,IATA,ICAO,TimeZone,City_Name,City_IATA,UTC_Offset_Hours,UTC_Offset_Seconds,Country_CodeA2,Country_CodeA3,Country_Name,GeoPointLat,GeoPointLong
0,Pilanesberg Intl,NTY,FAPN,Africa/Johannesburg,Sun City,NTY,2.0,7200.0,ZA,ZAF,South Africa,-25.333822,27.173358
1,Clovis Muni,CVN,KCVN,America/Denver,"Clovis, New Mexico",CVN,-6.0,-21600.0,US,USA,United States of America,34.425139,-103.079278
2,Cannon Afb,CVS,KCVS,America/Denver,"Clovis, New Mexico",CVN,-6.0,-21600.0,US,USA,United States of America,34.382775,-103.322147
3,Scammon Bay Airport,SCM,PACM,America/Nome,"Scammon Bay, Alaska",SCM,-8.0,-28800.0,US,USA,United States of America,61.845278,-165.571389
4,Kapit,KPI,NaN,Asia/Kuching,Kapit,KPI,8.0,28800.0,MY,MYS,Malaysia,2.017000,112.950000

In [5]:
df.isnull().sum()

AirportName              0
IATA                    20
ICAO                  1302
TimeZone                88
City_Name                0
City_IATA               62
UTC_Offset_Hours        88
UTC_Offset_Seconds      88
Country_CodeA2          14
Country_CodeA3           0
Country_Name             0
GeoPointLat              0
GeoPointLong             0
dtype: int64

In [9]:
def toldir(df):
    for col in df.columns:
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
            df[col].fillna(df[col].mean(), inplace=True)
    return df

In [12]:
toldir(df)

C:\Users\aaa\AppData\Local\Temp\ipykernel_3748\1182165533.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_3748\1182165533.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

,AirportName,IATA,ICAO,TimeZone,City_Name,City_IATA,UTC_Offset_Hours,UTC_Offset_Seconds,Country_CodeA2,Country_CodeA3,Country_Name,GeoPointLat,GeoPointLong
0,Pilanesberg Intl,NTY,FAPN,Africa/Johannesburg,Sun City,NTY,2.0,7200.0,ZA,ZAF,South Africa,-25.333822,27.173358
1,Clovis Muni,CVN,KCVN,America/Denver,"Clovis, New Mexico",CVN,-6.0,-21600.0,US,USA,United States of America,34.425139,-103.079278
2,Cannon Afb,CVS,KCVS,America/Denver,"Clovis, New Mexico",CVN,-6.0,-21600.0,US,USA,United States of America,34.382775,-103.322147
3,Scammon Bay Airport,SCM,PACM,America/Nome,"Scammon Bay, Alaska",SCM,-8.0,-28800.0,US,USA,United States of America,61.845278,-165.571389
4,Kapit,KPI,EDDB,Asia/Kuching,Kapit,KPI,8.0,28800.0,MY,MYS,Malaysia,2.017000,112.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6388,Prince Abdul Majeed Airport,ULH,OEAO,Africa/Cairo,AlUla,ULH,3.0,10800.0,SA,SAU,Saudi Arabia,26.479220,38.116890
6389,Yartsevo,YAE,EDDB,Asia/Krasnoyarsk,Yartsevo (Krasnoyarsk Krai),YAE,7.0,25200.0,RU,RUS,Russian Federation,60.251752,90.204909
6390,JIANSANJIANG,JSJ,EDDB,Asia/Shanghai,Fujin,JSJ,8.0,28800.0,CN,CHN,China,47.110000,132.660278
6391,KALUMBILA,UMB,EDDB,Africa/Lusaka,Kalumbila,UMB,2.0,7200.0,ZM,ZMB,Zambia,-12.253580,25.444320
6392,Omolon,-,EDDB,Asia/Kamchatka,Omolon,LON,12.0,43200.0,RU,RUS,Russian Federation,65.141200,160.330000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6393 entries, 0 to 6392
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AirportName         6393 non-null   object
 1   IATA                6393 non-null   object
 2   ICAO                6393 non-null   object
 3   TimeZone            6393 non-null   object
 4   City_Name           6393 non-null   object
 5   City_IATA           6393 non-null   object
 6   UTC_Offset_Hours    6393 non-null   float64
 7   UTC_Offset_Seconds  6393 non-null   float64
 8   Country_CodeA2      6393 non-null   object
 9   Country_CodeA3      6393 non-null   object
 10  Country_Name        6393 non-null   object
 11  GeoPointLat         6393 non-null   float64
 12  GeoPointLong        6393 non-null   float64
dtypes: float64(4), object(9)
memory usage: 649.4+ KB

In [17]:
df['IATA'].value_counts()

IATA
-      21
EGV     1
UMB     1
NTY     1
CVN     1
       ..
YLX     1
ULH     1
YAE     1
JSJ     1
DCY     1
Name: count, Length: 6373, dtype: int64

In [47]:
from sklearn.preprocessing import LabelEncoder

def encode_qil(df):
    encoding=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
           if df[col].nunique()<=6:
               dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
               df=pd.concat([df.drop(columns=col),dummies], axis=1)
           else:
               df[col]=encoding.fit_transform(df[col])
    return df

In [48]:
encode_qil(df)

,AirportName,IATA,ICAO,TimeZone,City_Name,City_IATA,UTC_Offset_Hours,UTC_Offset_Seconds,Country_CodeA2,Country_CodeA3,Country_Name,GeoPointLat,GeoPointLong
0,4395,3660,935,24,4857,3332,16,16,226,225,189,355,3788
1,1175,1075,1553,92,1044,1005,6,6,213,214,218,3093,768
2,909,1077,1554,92,1044,1005,6,6,213,214,218,3088,760
3,5046,4566,3237,139,4583,4154,4,4,213,214,218,5705,48
4,2642,2603,536,221,2309,2363,27,27,145,143,125,1333,5060
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6388,4537,5354,3072,12,88,4876,17,17,178,176,179,2480,4105
6389,6211,5839,536,219,5612,5262,26,26,176,174,171,5607,4741
6390,2464,2373,536,243,1612,2148,27,27,43,38,41,4525,5478
6391,2572,5365,536,35,2277,4886,16,16,227,226,228,799,3738
6392,4133,0,536,213,3691,2661,33,33,176,174,171,5844,5890

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6393 entries, 0 to 6392
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AirportName         6393 non-null   int64
 1   IATA                6393 non-null   int64
 2   ICAO                6393 non-null   int64
 3   TimeZone            6393 non-null   int64
 4   City_Name           6393 non-null   int64
 5   City_IATA           6393 non-null   int64
 6   UTC_Offset_Hours    6393 non-null   int64
 7   UTC_Offset_Seconds  6393 non-null   int64
 8   Country_CodeA2      6393 non-null   int64
 9   Country_CodeA3      6393 non-null   int64
 10  Country_Name        6393 non-null   int64
 11  GeoPointLat         6393 non-null   int64
 12  GeoPointLong        6393 non-null   int64
dtypes: int64(13)
memory usage: 649.4 KB

# 2-chi dataset

In [8]:
import pandas as pd
df=pd.read_csv('pdb_data_no_dups.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141401 entries, 0 to 141400
Data columns (total 14 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   structureId               141401 non-null  object
 1   classification            141399 non-null  object
 2   experimentalTechnique     141401 non-null  object
 3   macromoleculeType         137636 non-null  object
 4   residueCount              141401 non-null  int64
 5   resolution                128589 non-null  float64
 6   structureMolecularWeight  141401 non-null  float64
 7   crystallizationMethod     96242 non-null   object
 8   crystallizationTempK      97039 non-null   float64
 9   densityMatthews           124724 non-null  float64
 10  densityPercentSol         124749 non-null  float64
 11  pdbxDetails               118534 non-null  object
 12  phValue                   105110 non-null  float64
 13  publicationYear           117602 non-null  float64
dtypes: float64(7), int64(1), object(6)
memory usage: 15.1+ MB

In [11]:
df.isnull().sum()

structureId                     0
classification                  2
experimentalTechnique           0
macromoleculeType            3765
residueCount                    0
resolution                  12812
structureMolecularWeight        0
crystallizationMethod       45159
crystallizationTempK        44362
densityMatthews             16677
densityPercentSol           16652
pdbxDetails                 22867
phValue                     36291
publicationYear             23799
dtype: int64