# Data Preprocessing

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('synthetic_dna_dataset.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sample_ID        3000 non-null   object
 1   Sequence         2998 non-null   object
 2   GC_Content       2993 non-null   float64
 3   AT_Content       2987 non-null   float64
 4   Sequence_Length  2524 non-null   float64
 5   Num_A            2991 non-null   float64
 6   Num_T            2962 non-null   float64
 7   Num_C            2962 non-null   float64
 8   Num_G            2998 non-null   float64
 9   kmer_3_freq      2933 non-null   float64
 10  Mutation_Flag    2999 non-null   float64
 11  Class_Label      2962 non-null   object
 12  Disease_Risk     2992 non-null   object
dtypes: float64(9), object(4)
memory usage: 304.8+ KB

In [5]:
df.isnull().sum()

Sample_ID            0
Sequence             2
GC_Content           7
AT_Content          13
Sequence_Length    476
Num_A                9
Num_T               38
Num_C               38
Num_G                2
kmer_3_freq         67
Mutation_Flag        1
Class_Label         38
Disease_Risk         8
dtype: int64

In [6]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Class_Label,Disease_Risk
0,SAMPLE_1,CTTTCGGGATACTTTTGGGATGGTCTTGGTCAAGGGTTTTAGCCCG...,50.0,50.0,100.0,22.0,28.0,19.0,31.0,0.986,0.0,Bacteria,High
1,SAMPLE_2,TTGACCAAATTTGATTGGAAGTGGTAAGCGCGTATTCCTAGCATCA...,45.0,55.0,100.0,27.0,28.0,22.0,23.0,0.486,1.0,Virus,Medium
2,SAMPLE_3,GCGTGAGTTCTAATTTAAAAAGTCGTAACACGTACCCCGGCGTGTA...,51.0,49.0,100.0,26.0,23.0,30.0,21.0,0.367,1.0,Bacteria,Low
3,SAMPLE_4,ACTACGCGGACAAGAACCAACAGAACCTGGTTTTCGCAAGGGAGTG...,55.0,45.0,NaN,28.0,17.0,23.0,32.0,0.404,0.0,Human,Medium
4,SAMPLE_5,TTCAATGCAGATTGAAAGTTACTTTCATCTGCCCTATGGGTCCCTT...,46.0,54.0,NaN,24.0,30.0,25.0,21.0,0.818,0.0,Human,High

# Missing qiymatlarni yo'qotish

In [7]:
for col in df.columns:
    if df[col].isnull().sum()<4:
       if df[col].isnull().sum() < 4:
        df.dropna(subset=[col], inplace=True)
    elif df[col].isnull().sum()>2500:
        df.drop(columns=[col], inplace=True)
    elif df[col].dtype=="float64":
        df[col].fillna(df[col].mean(),inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\aaa\AppData\Local\Temp\ipykernel_18396\3488010963.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_18396\3488010963.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_18396\3488010963.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sample_ID        2997 non-null   object
 1   Sequence         2997 non-null   object
 2   GC_Content       2997 non-null   float64
 3   AT_Content       2997 non-null   float64
 4   Sequence_Length  2997 non-null   float64
 5   Num_A            2997 non-null   float64
 6   Num_T            2997 non-null   float64
 7   Num_C            2997 non-null   float64
 8   Num_G            2997 non-null   float64
 9   kmer_3_freq      2997 non-null   float64
 10  Mutation_Flag    2997 non-null   float64
 11  Class_Label      2997 non-null   object
 12  Disease_Risk     2997 non-null   object
dtypes: float64(9), object(4)
memory usage: 327.8+ KB

# Encoding qilish

In [9]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, TargetEncoder
label_encode=LabelEncoder()
ordinal_encode=OrdinalEncoder()
target_encode=TargetEncoder()

In [10]:
ordinal_encode = OrdinalEncoder(categories=[["Low", "Medium", "High"]])
df["Disease_Risk_encode"] = ordinal_encode.fit_transform(df[["Disease_Risk"]])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sample_ID            2997 non-null   object
 1   Sequence             2997 non-null   object
 2   GC_Content           2997 non-null   float64
 3   AT_Content           2997 non-null   float64
 4   Sequence_Length      2997 non-null   float64
 5   Num_A                2997 non-null   float64
 6   Num_T                2997 non-null   float64
 7   Num_C                2997 non-null   float64
 8   Num_G                2997 non-null   float64
 9   kmer_3_freq          2997 non-null   float64
 10  Mutation_Flag        2997 non-null   float64
 11  Class_Label          2997 non-null   object
 12  Disease_Risk         2997 non-null   object
 13  Disease_Risk_encode  2997 non-null   float64
dtypes: float64(10), object(4)
memory usage: 351.2+ KB

In [12]:
df.drop(columns=['Disease_Risk'], axis=1, inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sample_ID            2997 non-null   object
 1   Sequence             2997 non-null   object
 2   GC_Content           2997 non-null   float64
 3   AT_Content           2997 non-null   float64
 4   Sequence_Length      2997 non-null   float64
 5   Num_A                2997 non-null   float64
 6   Num_T                2997 non-null   float64
 7   Num_C                2997 non-null   float64
 8   Num_G                2997 non-null   float64
 9   kmer_3_freq          2997 non-null   float64
 10  Mutation_Flag        2997 non-null   float64
 11  Class_Label          2997 non-null   object
 12  Disease_Risk_encode  2997 non-null   float64
dtypes: float64(10), object(3)
memory usage: 327.8+ KB

In [14]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Class_Label,Disease_Risk_encode
0,SAMPLE_1,CTTTCGGGATACTTTTGGGATGGTCTTGGTCAAGGGTTTTAGCCCG...,50.0,50.0,100.0,22.0,28.0,19.0,31.0,0.986,0.0,Bacteria,2.0
1,SAMPLE_2,TTGACCAAATTTGATTGGAAGTGGTAAGCGCGTATTCCTAGCATCA...,45.0,55.0,100.0,27.0,28.0,22.0,23.0,0.486,1.0,Virus,1.0
2,SAMPLE_3,GCGTGAGTTCTAATTTAAAAAGTCGTAACACGTACCCCGGCGTGTA...,51.0,49.0,100.0,26.0,23.0,30.0,21.0,0.367,1.0,Bacteria,0.0
3,SAMPLE_4,ACTACGCGGACAAGAACCAACAGAACCTGGTTTTCGCAAGGGAGTG...,55.0,45.0,100.0,28.0,17.0,23.0,32.0,0.404,0.0,Human,1.0
4,SAMPLE_5,TTCAATGCAGATTGAAAGTTACTTTCATCTGCCCTATGGGTCCCTT...,46.0,54.0,100.0,24.0,30.0,25.0,21.0,0.818,0.0,Human,2.0

In [23]:
for col in df.columns:
    label_encode=LabelEncoder()
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix='col', dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col]=label_encode.fit_transform(df[col])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Sample_ID            2997 non-null   int64
 1   Sequence             2997 non-null   int64
 2   GC_Content           2997 non-null   int64
 3   AT_Content           2997 non-null   int64
 4   Sequence_Length      2997 non-null   int64
 5   Num_A                2997 non-null   int64
 6   Num_T                2997 non-null   int64
 7   Num_C                2997 non-null   int64
 8   Num_G                2997 non-null   int64
 9   kmer_3_freq          2997 non-null   int64
 10  Mutation_Flag        2997 non-null   int64
 11  Disease_Risk_encode  2997 non-null   int64
 12  col_Bacteria         2997 non-null   int64
 13  col_Human            2997 non-null   int64
 14  col_Plant            2997 non-null   int64
 15  col_Virus            2997 non-null   int64
dtypes: int64(16)
memory usage: 398.0 KB

In [25]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Disease_Risk_encode,col_Bacteria,col_Human,col_Plant,col_Virus
0,0,1491,16,17,0,11,19,9,19,854,0,2,1,0,0,0
1,1110,2901,11,22,0,17,19,12,11,375,1,1,0,0,0,1
2,2221,1801,18,15,0,16,13,21,9,260,1,0,1,0,0,0
3,2333,333,22,11,0,18,7,13,20,296,0,1,0,1,0,0
4,2444,2851,12,21,0,13,21,15,9,692,0,2,0,1,0,0

In [22]:
df['Sequence'].value_counts().sum()

np.int64(2997)

# Scaling qilish

In [26]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
standard=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [28]:
a_minmax=['Sample_ID','Sequence','kmer_3_freq']
df[a_minmax]=minmax.fit_transform(df[a_minmax])

In [29]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Disease_Risk_encode,col_Bacteria,col_Human,col_Plant,col_Virus
0,0.000000,0.497664,16,17,0,11,19,9,19,0.985006,0,2,1,0,0,0
1,0.370494,0.968291,11,22,0,17,19,12,11,0.432526,1,1,0,0,0,1
2,0.741322,0.601135,18,15,0,16,13,21,9,0.299885,1,0,1,0,0,0
3,0.778705,0.111148,22,11,0,18,7,13,20,0.341407,0,1,0,1,0,0
4,0.815754,0.951602,12,21,0,13,21,15,9,0.798155,0,2,0,1,0,0

In [31]:
b_standard=['GC_Content','AT_Content','Num_A','Num_T','Num_C','Num_G']
df[b_standard]=standard.fit_transform(df[b_standard])

In [32]:
df.head()

,Sample_ID,Sequence,GC_Content,AT_Content,Sequence_Length,Num_A,Num_T,Num_C,Num_G,kmer_3_freq,Mutation_Flag,Disease_Risk_encode,col_Bacteria,col_Human,col_Plant,col_Virus
0,0.000000,0.497664,-0.108083,0.110079,0,-0.739501,0.757206,-1.367995,1.359466,0.985006,0,2,1,0,0,0
1,0.370494,0.968291,-1.023120,1.026489,0,0.532520,0.757206,-0.732880,-0.489032,0.432526,1,1,0,0,0,1
2,0.741322,0.601135,0.257933,-0.256485,0,0.320516,-0.521179,1.172466,-0.951156,0.299885,1,0,1,0,0,0
3,0.778705,0.111148,0.989963,-0.989613,0,0.744523,-1.799564,-0.521175,1.590529,0.341407,0,1,0,1,0,0
4,0.815754,0.951602,-0.840113,0.843207,0,-0.315494,1.183334,-0.097764,-0.951156,0.798155,0,2,0,1,0,0