# Data preprocessing 1-qism

In [ ]:
# missing valuelar bilan ishlash

In [ ]:
import pandas as pd #pandas kutubxonasini o'rnatib olish uchun kod

In [ ]:
df=pd.read_csv('IMDB_Movies_Dataset.csv') #datasetimizni o'ng tomonga olib olish uchun ishlatiladigan kod hiosblanadi

In [4]:
df.info() # data haqida umumiy ma'lumotga ega bo'lish kodi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4989 entries, 0 to 4988
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          3055 non-null   float64
 6   Cast               4982 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 506.8+ KB

In [5]:
df.isnull().sum() # tushib qoldirilgan qiymatlarni aniqlash

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore            1934
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [6]:
df.head(1) #datasetimiz boshidan 1 qatarini konsolga chiqartirish uchun ishlatiladigan kod

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Budget,Worldwide Gross,Runtime
0,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$25,000,000 (estimated)","$29,332,133",2 hours 22 minutes

In [8]:
df['Writer']

0                            Stephen King, Frank Darabont
1           Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue
2                        Mario Puzo, Francis Ford Coppola
3                                 Umur Bugay, Rifat Ilgaz
4                        Rani Burra, Ram Mohan, Yûgô Sakô
                              ...
4984         Jorge Guerricaechevarría, Álex de la Iglesia
4985                     Roy Chanslor, Arthur Conan Doyle
4986                        Hiroshi Takahashi, Shôgo Mutô
4987    Ruben Alves, Luc-Olivier Veuve, Jean-André Yerlès
4988                                      Kwak Kyung-taek
Name: Writer, Length: 4989, dtype: object

In [ ]:
df=df.dropna(subset='Writer', axis=0)# drop qilish kodi bo'lib faqat tushib qolgan qiymatlar ko'p bo'lmagan holatlardagina ishlata olamiz
# df=df.drop('Writer', axis=1) bu ustunlar bo'yicha drop qilish mumkin, ustunlar bo'yicha drop qilish qiymatlarimizda tushib qolgan holatlar ko'p bo'lganda ishlatamiz

In [12]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  0
Metascore            1933
Cast                    6
Release Date            0
Country of Origin       3
Languages              21
Budget               2337
Worldwide Gross      1093
Runtime                 0
dtype: int64

In [13]:
df.head()

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Budget,Worldwide Gross,Runtime
0,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$25,000,000 (estimated)","$29,332,133",2 hours 22 minutes
1,1,Attack on Titan the Movie: The Last Attack,9.3,Yûichirô Hayashi,"Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue",NaN,"Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue,...","November 8, 2024 (Japan)",Japan,Japanese,NaN,"$3,513,659",2 hours 25 minutes
2,2,The Godfather,9.2,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",100.0,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",1978 (India),United States,"English, Italian, Latin","$6,000,000 (estimated)","$250,342,198",2 hours 55 minutes
3,3,Hababam Sinifi,9.2,Ertem Egilmez,"Umur Bugay, Rifat Ilgaz",NaN,"Münir Özkul, Tarik Akan, Halit Akçatepe, Kemal...","April 1, 1975 (Turkey)",Turkey,Turkish,NaN,NaN,1 hour 25 minutes
4,4,Ramayana: The Legend of Prince Rama,9.2,"Ram Mohan, Yûgô Sakô, Koichi Saski","Rani Burra, Ram Mohan, Yûgô Sakô",NaN,"Arun Govil, Nikhil Kapoor, Edie Mirman, Rael P...","September 25, 2001 (India)","India, Japan",English,NaN,NaN,2 hours 15 minutes

In [ ]:
df=df.dropna(subset='Country of Origin', axis=0) # qatorlar bo'yicha drop qilish kodi

In [15]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  0
Metascore            1930
Cast                    6
Release Date            0
Country of Origin       0
Languages              18
Budget               2334
Worldwide Gross      1091
Runtime                 0
dtype: int64

In [ ]:
df=df.drop('Budget', axis=1) #drop ustun bo'yicha qilganimizda dropna qilmasdan faqat "drop" qilamiz halos va yana "subset" ham bo'lmaydi

In [19]:
df.head()

,Unnamed: 0,Title,Average Rating,Director,Writer,Metascore,Cast,Release Date,Country of Origin,Languages,Worldwide Gross,Runtime
0,0,The Shawshank Redemption,9.3,Frank Darabont,"Stephen King, Frank Darabont",82.0,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","October 14, 1994 (India)",United States,English,"$29,332,133",2 hours 22 minutes
1,1,Attack on Titan the Movie: The Last Attack,9.3,Yûichirô Hayashi,"Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue",NaN,"Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue,...","November 8, 2024 (Japan)",Japan,Japanese,"$3,513,659",2 hours 25 minutes
2,2,The Godfather,9.2,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",100.0,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",1978 (India),United States,"English, Italian, Latin","$250,342,198",2 hours 55 minutes
3,3,Hababam Sinifi,9.2,Ertem Egilmez,"Umur Bugay, Rifat Ilgaz",NaN,"Münir Özkul, Tarik Akan, Halit Akçatepe, Kemal...","April 1, 1975 (Turkey)",Turkey,Turkish,NaN,1 hour 25 minutes
4,4,Ramayana: The Legend of Prince Rama,9.2,"Ram Mohan, Yûgô Sakô, Koichi Saski","Rani Burra, Ram Mohan, Yûgô Sakô",NaN,"Arun Govil, Nikhil Kapoor, Edie Mirman, Rael P...","September 25, 2001 (India)","India, Japan",English,NaN,2 hours 15 minutes

In [20]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  0
Metascore            1930
Cast                    6
Release Date            0
Country of Origin       0
Languages              18
Worldwide Gross      1091
Runtime                 0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4989 entries, 0 to 4988
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          3055 non-null   float64
 6   Cast               4982 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 506.8+ KB

In [8]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore            1934
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

# Mean bilan to'ldirish

In [ ]:
# Mean bilan to'dirish bu berilgan qiymatlar orasidagi tushib qolganni to'ldirish uchun berilgan qiymatlarni qo'shib umumiyga bo'lib qo'yamiz.(Raqamli qiymatlar bilan ishlaymiz)(Intr va float bo'lganda ishlata olamiz halos)

In [9]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore            1934
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [12]:
df['Metascore']

0        82.000000
1        74.684452
2       100.000000
3        74.684452
4        74.684452
           ...
4984     74.684452
4985     74.684452
4986     74.684452
4987     74.684452
4988     74.684452
Name: Metascore, Length: 4989, dtype: float64

In [ ]:
df['Metascore']=df['Metascore'].fillna(df['Metascore'].mean()) # Mean bilan to'dirishda ishlatiladigan kod bo'lib faqat raqamli qiymatlar bilangina ishlashimiz mumkin bo'ladi
# df['Metascore'].fillna(df['Metascore'].mean(), inplace=True) # bu yuqoridagi kodimizga alternativ kod bo'lib

In [11]:
df.isnull().sum() #tushib qolgan qiymatlarni aniqlash kodi

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [13]:
df['Metascore'] # aynan bir qiymat haqida ma'lumot olish uchun

0        82.000000
1        74.684452
2       100.000000
3        74.684452
4        74.684452
           ...
4984     74.684452
4985     74.684452
4986     74.684452
4987     74.684452
4988     74.684452
Name: Metascore, Length: 4989, dtype: float64

# Mode Bilan ishlash

In [ ]:
# mode bu tushirilib qoldirilgan qiymatni eng kop takrorlangan qiymat bilan to'ldirib ketish usuli hioblanadi, bunda meandan farqli o'laroq raqamli va stringli qiymatlar bilan ham ishlatish munmkin

In [14]:
df.isnull().sum() # bu kod DataFrame (df) ichidagi har bir ustunda nechta bo'sh qiymat (NaN / None) borligini hisoblab beradi. Ya'ni, qaysi ustunda nechta ma'lumot yetishmayapti — shuni ko'rsatadi.

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [ ]:
df['Cast'].fillna(df['Cast'].mode()[0],inplace=True) # Tushirib qoldirilgan qiymatlarni mode bilan to'ldirish kodi hisoblanadi
#df['Cast'] - to'ldirish kerak bo'lgan ustun
# fillna(df['Cast'] - to'dir va df['Cast'] ni ol va uni eng ko'p takrorlangan qiymat bilan to'dir
# [0] - bu eng ko'p takrorlangan qiymat hisoblanadi
# (inplace=False)  bu amal natijasini bevosita (to'g'ridan-to'g'ri) mavjud ma'lumotlarga qo‘llash degan ma'noni anglatadi. Ya'ni, inplace=True bo‘lsa:

#                                    O‘zgarish asl DataFrame yoki Series ichida darhol bajariladi.

#                                     Yangi nusxa (copy) yaratilmaydi.

# Agar inplace=False (yoki inplace yozilmasa), u holda o‘zgarishlar yangi nusxada aks etadi va asl obyekt o‘zgarishsiz qoladi.

In [17]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

# Median bilan ishlash

In [ ]:
# Median — bu o'rtacha qiymat, ya'ni ma'lumotlar to‘plamidagi o‘rtadagi element.
#                   Agar sonlar soni toq bo'lsa → o'rtadagi bitta son median bo'ladi.
#                   Agar sonlar soni juft bo'lsa → o'rtadagi ikkita son olinadi va ularning o'rtacha arifmetik qiymati median bo'ladi.
# toq sonli qiymatlar uchun:
# Sonlar: 3, 7, 9
# Tartiblash: 3, 7, 9
# Median: 7 (o‘rtadagi son)

# juft sonli qiymatlar uchun:
# Sonlar: 2, 4, 6, 8
# Tartiblash: 2, 4, 6, 8
# Median: (4 + 6) / 2 = 5

In [27]:
df.describe() # Pandas kutubxonasida ishlatiladigan statistik xulosa (summary statistics) chiqaruvchi funksiyadir. 
# ma'lumotlaringizni umumiy ko'rib chiqish, taqqoslash, va anomaliyalarni aniqlash imkonini beradi.
# ma'lumotlar to'plamidagi (dataframe ichidagi) sonli ustunlar uchun quyidagi asosiy statistik ma'lumotlarni beradi:
# count	4989.000000	4989.000000	4989.000000  Nechta qiymat borligi (missing qiymatlar hisobga olinmaydi)
# mean	248.951493	7.632892	74.684452    O'rtacha qiymat (average)
# std	144.036753	0.365243	9.623608     Standart og'ish (qiymatlarning tarqalishini o'lchaydi)
# min	0.000000	7.200000	25.000000    Eng kichik qiymat
# 25%	124.000000	7.300000	73.000000    1-kvartil (pastki 25% qiymat)
# 50%	249.000000	7.600000	74.684452    	O'rtadagi qiymat (median)
# 75%	374.000000	7.800000	78.000000      	3-kvartil (yuqori 25% qiymat)
# max 499.000000	9.300000	100.000000      Eng katta qiymat

        Unnamed: 0  Average Rating    Metascore
count  4989.000000     4989.000000  4989.000000
mean    248.951493        7.632892    74.684452
std     144.036753        0.365243     9.623608
min       0.000000        7.200000    25.000000
25%     124.000000        7.300000    73.000000
50%     249.000000        7.600000    74.684452
75%     374.000000        7.800000    78.000000
max     499.000000        9.300000   100.000000

In [25]:
df['Country of Origin'].value_counts() #bu kod DataFrame (df) ichidagi 'Country of Origin' ustunida har bir turli qiymat (ya'ni har bir mamlakat) nechta marta uchraganini hisoblab beradi.

Country of Origin
United States                                                        1624
India                                                                 583
Japan                                                                 206
United Kingdom, United States                                         167
United Kingdom                                                        164
                                                                     ...
Denmark, Germany, Norway, France, Sweden, Finland, Czech Republic       1
Austria, United States                                                  1
Estonia, Georgia                                                        1
Switzerland, France                                                     1
Spain, United Kingdom, Isle of Man                                      1
Name: count, Length: 812, dtype: int64

In [26]:
df['Country of Origin'].nunique() # bu kod 'Country of Origin' ustunidagi takrorlanmaydigan (noyob) qiymatlarning sonini hisoblaydi. Ya'ni, nechta turli mamlakat borligini topadi.

812

In [28]:
df['Country of Origin'].fillna(df['Country of Origin'].median(),inplace=True) # bunda faqat raqamli qiymatlar bilan ishlatiladi

TypeError: Cannot convert ['United States' 'Japan' 'United States' ... 'Japan' 'France'
 'South Korea'] to numeric

In [29]:
df['Unnamed: 0'].fillna(df['Unnamed: 0'].median(),inplace=True) 
# df['Unnamed: 0']
#→ DataFrame (df) ichidagi 'Unnamed: 0' ustunini oladi.

#.fillna(df['Unnamed: 0'].median()) → Ushbu ustundagi bo'sh qiymatlarni (NaN) shu ustunning median qiymati bilan to'ldiradi.
#Median — o'rtacha tartibdagi qiymat (ortib borish tartibida joylashtirilganda o'rta joydagi qiymat).

#inplace=True → Olingan natijani asosiy dfga o'zgartirib saqlaydi.(Yangi nusxa yaratmaydi, o'zi o'zgaradi.)

C:\Users\aaa\AppData\Local\Temp\ipykernel_3988\1512424970.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unnamed: 0'].fillna(df['Unnamed: 0'].median(),inplace=True)

In [30]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4989 entries, 0 to 4988
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          4989 non-null   float64
 6   Cast               4989 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 506.8+ KB

# fixed bilan ishlash

In [ ]:
# fixed - o'zimiz istalgan qiytmat bilan to'ldirish

In [32]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4989 entries, 0 to 4988
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4989 non-null   int64
 1   Title              4989 non-null   object
 2   Average Rating     4989 non-null   float64
 3   Director           4989 non-null   object
 4   Writer             4988 non-null   object
 5   Metascore          4989 non-null   float64
 6   Cast               4989 non-null   object
 7   Release Date       4989 non-null   object
 8   Country of Origin  4986 non-null   object
 9   Languages          4968 non-null   object
 10  Budget             2651 non-null   object
 11  Worldwide Gross    3895 non-null   object
 12  Runtime            4989 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 506.8+ KB

In [33]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [34]:
df['Languages'].value_counts()

Languages
English                                                    1514
Hindi                                                       239
Japanese                                                    160
English, Spanish                                            142
French                                                      130
                                                           ...
English, Japanese, Mandarin, French, Cantonese, Spanish       1
Cantonese, English, Japanese                                  1
Dutch, French, Flemish                                        1
Arabic, English, Turkish                                      1
Zulu, Sotho, Xhosa, Afrikaans, English                        1
Name: count, Length: 1084, dtype: int64

In [35]:
df['Languages'].fillna('English',inplace=True)

In [36]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages               0
Budget               2338
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [38]:
df=df.drop('Budget', axis=1)

In [39]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  1
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages               0
Worldwide Gross      1094
Runtime                 0
dtype: int64

In [40]:
df=df.dropna(subset='Writer', axis=0)

In [41]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          0
Director                0
Writer                  0
Metascore               0
Cast                    0
Release Date            0
Country of Origin       3
Languages               0
Worldwide Gross      1093
Runtime                 0
dtype: int64

In [42]:
df['Worldwide Gross']

0        $29,332,133
1         $3,513,659
2       $250,342,198
3                NaN
4                NaN
            ...
4984        $290,754
4985             NaN
4986     $29,893,636
4987     $17,871,370
4988        $550,031
Name: Worldwide Gross, Length: 4988, dtype: object

In [ ]:
missing_columns=['Country of Origin','Worldwide Gross']
df[missing_columns]=df[missing_columns].fillna(df[missing_columns].iloc[0])
# missing_columns ro'yxat
#biz 2 ta ustun nomini ro'yxatga oldik:

#'Country of Origin'

#'Worldwide Gross'

#df[missing_columns]
#→ DataFrame (df) dan faqat shu 2 ta ustunni ajratib oldik.

#.fillna(df[missing_columns].iloc[0])→ Har bir ustundagi NaN (missing) qiymatlarni shu ustunning birinchi satr (iloc[0]) qiymati bilan to'ldirdi. Bu usul tez va oddiy.

#Lekin katta datasetlar va noaniq missinglar ko'p bo'lsa, har doim first row (iloc[0]) bilan to'ldirish xatolarga olib kelishi mumkin.

# Statistika bo'yicha: katta datasetlar uchun mean, median yoki mode bilan to'ldirish tavsiya etiladi.inplace ishlatilmagan, shuning uchun to'ldirilgan natijani yana df[missing_columns] ga qaytadan saqlab qo'yyapsiz.

# vazifa

In [3]:
df=pd.read_csv('Nashville Accidents Jan 2018 - Apl 2025.csv')

NameError: name 'pd' is not defined

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216117 entries, 0 to 216116
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Accident Number             216117 non-null  int64
 1   Date and Time               216117 non-null  object
 2   Number of Motor Vehicles    216113 non-null  float64
 3   Number of Injuries          216114 non-null  float64
 4   Number of Fatalities        216114 non-null  float64
 5   Property Damage             17640 non-null   object
 6   Hit and Run                 216103 non-null  object
 7   Collision Type Description  203143 non-null  object
 8   Weather Description         194653 non-null  object
 9   Illumination Description    202657 non-null  object
 10  Street Address              215881 non-null  object
 11  City                        216113 non-null  object
 12  State                       216113 non-null  object
 13  Precinct                    216007 non-null  object
 14  Lat                         216115 non-null  float64
 15  Long                        216115 non-null  float64
 16  HarmfulCodes                196872 non-null  object
 17  HarmfulDescriptions         194682 non-null  object
 18  ObjectId                    216117 non-null  int64
 19  Zip Code                    215974 non-null  float64
 20  RPA                         216012 non-null  float64
 21  Weather                     194653 non-null  float64
 22  IlluACCIDEmination          202661 non-null  float64
 23  Collision Type              203143 non-null  float64
 24  Reporting Officer           216102 non-null  float64
 25  x                           216115 non-null  float64
 26  y                           216115 non-null  float64
dtypes: float64(13), int64(2), object(12)
memory usage: 44.5+ MB

In [5]:
df.isnull().sum()

NameError: name 'df' is not defined

In [48]:
df.head(10)

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Weather Description,Illumination Description,...,HarmfulDescriptions,ObjectId,Zip Code,RPA,Weather,IlluACCIDEmination,Collision Type,Reporting Officer,x,y
0,2008473471,7/14/2018 11:00:00 PM,2.0,2.0,0.0,NaN,N,ANGLE,NO ADVERSE CONDITIONS,NaN,...,NaN,1,37208.0,4525.0,1.0,1.0,4.0,225845.0,-9.664843e+06,4.323742e+06
1,2008787228,11/16/2018 9:33:00 AM,1.0,1.0,0.0,NaN,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,NO ADVERSE CONDITIONS,NaN,...,NaN,2,37203.0,5401.0,1.0,3.0,0.0,475881.0,-9.662645e+06,4.322558e+06
2,2009131786,2/19/2019 10:42:00 PM,1.0,1.0,0.0,NaN,N,HEAD-ON,NO ADVERSE CONDITIONS,NaN,...,NaN,3,37218.0,3235.0,1.0,1.0,2.0,562528.0,-9.674832e+06,4.329570e+06
3,2009418107,5/27/2019 9:00:00 PM,2.0,0.0,0.0,NaN,Y,REAR END,NO ADVERSE CONDITIONS,NaN,...,NaN,4,NaN,4311.0,1.0,1.0,1.0,571315.0,-9.659749e+06,4.323487e+06
4,20120135824,3/8/2021 6:05:00 PM,2.0,1.0,0.0,NaN,N,Front to Rear,CLEAR,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT,5,37207.0,1863.0,21.0,1.0,11.0,473670.0,-9.659079e+06,4.328993e+06
5,20130207124,7/23/2019 3:46:00 PM,2.0,0.0,0.0,NaN,N,Front to Rear,CLEAR,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT,6,37210.0,83043.0,21.0,1.0,11.0,716886.0,-9.655106e+06,4.317900e+06
6,20130311458,8/23/2023 1:00:00 PM,2.0,0.0,0.0,NaN,N,SIDESWIPE - SAME DIRECTION,CLEAR,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT,7,37213.0,1104.0,21.0,1.0,5.0,834807.0,-9.658781e+06,4.323872e+06
7,20131173280,12/22/2020 6:00:00 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20150316352,4/9/2018 2:19:00 AM,2.0,0.0,0.0,NaN,Y,ANGLE,CLEAR,DARK - LIGHTED,...,MOTOR VEHICLE IN TRANSPORT;WALL,9,37013.0,8806.0,21.0,3.0,4.0,110090.0,-9.642834e+06,4.302885e+06
9,20150550257,7/23/2019 11:40:00 PM,2.0,1.0,0.0,NaN,N,ANGLE,CLOUDY,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT,10,37211.0,8431.0,22.0,1.0,4.0,420040.0,-9.655734e+06,4.314192e+06

In [56]:
df.tail()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Weather Description,Illumination Description,...,HarmfulDescriptions,ObjectId,Zip Code,RPA,Weather,IlluACCIDEmination,Collision Type,Reporting Officer,x,y
216058,20250213438,4/5/2025 3:27:00 AM,1.0,0.0,0.0,Y,Y,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,UTILITY POLE,216059,37138.0,9609.0,21.0,3.0,0.0,409192.0,-9.646279e+06,4.335883e+06
216061,20250213488,4/5/2025 3:47:00 AM,1.0,1.0,0.0,Y,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,OTHER FIXED OBJECTS,216062,37076.0,9727.0,21.0,3.0,0.0,4001484.0,-9.639368e+06,4.330246e+06
216080,20250214198,4/5/2025 7:55:00 AM,1.0,0.0,0.0,Y,Y,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,CONCRETE TRAFFIC BARRIER,216081,37203.0,4109.0,21.0,3.0,0.0,493301.0,-9.660438e+06,4.322847e+06
216099,20250214490,4/5/2025 7:25:00 PM,1.0,0.0,0.0,Y,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DAYLIGHT,...,CULVERT,216100,37218.0,3117.0,21.0,1.0,0.0,207027.0,-9.666542e+06,4.326673e+06
216111,20250214850,4/5/2025 7:30:00 PM,1.0,0.0,0.0,Y,Y,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,RAIN,DAYLIGHT,...,BUILDING,216112,37080.0,3315.0,2.0,1.0,0.0,4015361.0,-9.675728e+06,4.346292e+06

In [1]:
#df=df.dropna(subset='Number of Motor Vehicles', axis=0)
#df=df.dropna(subset='Number of Injuries', axis=0)
#df=df.dropna(subset='Number of Fatalities', axis=0)
df = df.dropna(subset=['Number of Motor Vehicles', 'Number of Injuries', 'Number of Fatalities', 'City', 'State', 'Lat', 'Long', 'x', 'y'], axis=0)

NameError: name 'df' is not defined

In [61]:
df.isnull().sum()

Accident Number               0
Date and Time                 0
Number of Motor Vehicles      0
Number of Injuries            0
Number of Fatalities          0
Property Damage               0
Hit and Run                   0
Collision Type Description    0
Weather Description           0
Illumination Description      0
Street Address                0
City                          0
State                         0
Precinct                      0
Lat                           0
Long                          0
HarmfulCodes                  0
HarmfulDescriptions           0
ObjectId                      0
Zip Code                      0
RPA                           0
Weather                       0
IlluACCIDEmination            0
Collision Type                0
Reporting Officer             0
x                             0
y                             0
dtype: int64