# Final exam

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Indian_Kids_Screen_Time.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     6494 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

# Missing qiymatlarni to'ldirish

In [4]:
df.isnull().sum()

Age                                     0
Gender                                  0
Avg_Daily_Screen_Time_hr                0
Primary_Device                          0
Exceeded_Recommended_Limit              0
Educational_to_Recreational_Ratio       0
Health_Impacts                       3218
Urban_or_Rural                          0
dtype: int64

In [5]:
df['Health_Impacts']

0                Poor Sleep, Eye Strain
1                            Poor Sleep
2                            Poor Sleep
3                                   NaN
4                   Poor Sleep, Anxiety
                     ...
9707                         Poor Sleep
9708                         Poor Sleep
9709    Poor Sleep, Eye Strain, Anxiety
9710                         Poor Sleep
9711                            Anxiety
Name: Health_Impacts, Length: 9712, dtype: object

In [6]:
df['Health_Impacts'].fillna(df['Health_Impacts'].mode()[0], inplace=True)

In [7]:
df.isnull().sum()

Age                                  0
Gender                               0
Avg_Daily_Screen_Time_hr             0
Primary_Device                       0
Exceeded_Recommended_Limit           0
Educational_to_Recreational_Ratio    0
Health_Impacts                       0
Urban_or_Rural                       0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Gender                             9712 non-null   object
 2   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 3   Primary_Device                     9712 non-null   object
 4   Exceeded_Recommended_Limit         9712 non-null   bool
 5   Educational_to_Recreational_Ratio  9712 non-null   float64
 6   Health_Impacts                     9712 non-null   object
 7   Urban_or_Rural                     9712 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 540.7+ KB

# Encoding qilish

In [10]:
df.head(20)

,Age,Gender,Avg_Daily_Screen_Time_hr,Primary_Device,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Health_Impacts,Urban_or_Rural
0,14,Male,3.99,Smartphone,True,0.42,"Poor Sleep, Eye Strain",Urban
1,11,Female,4.61,Laptop,True,0.30,Poor Sleep,Urban
2,18,Female,3.73,TV,True,0.32,Poor Sleep,Urban
3,15,Female,1.21,Laptop,False,0.39,Poor Sleep,Urban
4,12,Female,5.89,Smartphone,True,0.49,"Poor Sleep, Anxiety",Urban
5,14,Female,4.88,Smartphone,True,0.44,Poor Sleep,Urban
6,17,Male,2.97,TV,False,0.48,Poor Sleep,Rural
7,10,Male,2.74,TV,True,0.54,Poor Sleep,Urban
8,14,Male,4.61,Laptop,True,0.36,"Poor Sleep, Anxiety",Rural
9,18,Male,3.24,Tablet,True,0.48,"Poor Sleep, Obesity Risk",Urban
10,18,Male,3.53,Tablet,True,0.44,Poor Sleep,Rural
11,15,Female,4.94,TV,True,0.36,Poor Sleep,Rural
12,12,Male,4.59,Smartphone,True,0.43,Poor Sleep,Urban
13,11,Male,6.08,TV,True,0.48,Eye Strain,Rural
14,15,Male,6.15,Smartphone,True,0.40,Poor Sleep,Urban
15,15,Female,3.69,Smartphone,True,0.34,Poor Sleep,Urban
16,10,Female,7.10,Smartphone,True,0.43,"Poor Sleep, Eye Strain",Rural
17,13,Female,6.98,Smartphone,True,0.48,Obesity Risk,Urban
18,12,Male,3.82,Smartphone,True,0.40,Anxiety,Urban
19,9,Female,0.00,TV,False,0.42,Poor Sleep,Urban

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [15]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
    else:
        df[col]=encoder.fit_transform(df[col])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   int64
 2   Exceeded_Recommended_Limit         9712 non-null   int64
 3   Educational_to_Recreational_Ratio  9712 non-null   int64
 4   Health_Impacts                     9712 non-null   object
 5   Gender_Female                      9712 non-null   int64
 6   Gender_Male                        9712 non-null   int64
 7   Primary_Device_Laptop              9712 non-null   int64
 8   Primary_Device_Smartphone          9712 non-null   int64
 9   Primary_Device_TV                  9712 non-null   int64
 10  Primary_Device_Tablet              9712 non-null   int64
 11  Urban_or_Rural_Rural               9712 non-null   int64
 12  Urban_or_Rural_Urban               9712 non-null   int64
dtypes: int64(12), object(1)
memory usage: 986.5+ KB

In [21]:
df['Health_Impacts'].value_counts()

Health_Impacts
Poor Sleep                                       5486
Poor Sleep, Eye Strain                            979
Eye Strain                                        644
Poor Sleep, Anxiety                               608
Poor Sleep, Obesity Risk                          452
Anxiety                                           385
Poor Sleep, Eye Strain, Anxiety                   258
Obesity Risk                                      252
Poor Sleep, Eye Strain, Obesity Risk              188
Eye Strain, Anxiety                               135
Eye Strain, Obesity Risk                          106
Poor Sleep, Anxiety, Obesity Risk                  78
Anxiety, Obesity Risk                              69
Poor Sleep, Eye Strain, Anxiety, Obesity Risk      37
Eye Strain, Anxiety, Obesity Risk                  35
Name: count, dtype: int64

In [22]:
freq_encode=df['Health_Impacts'].value_counts()
df['Health_freq']=df['Health_Impacts'].map(freq_encode)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   int64
 2   Exceeded_Recommended_Limit         9712 non-null   int64
 3   Educational_to_Recreational_Ratio  9712 non-null   int64
 4   Health_Impacts                     9712 non-null   object
 5   Gender_Female                      9712 non-null   int64
 6   Gender_Male                        9712 non-null   int64
 7   Primary_Device_Laptop              9712 non-null   int64
 8   Primary_Device_Smartphone          9712 non-null   int64
 9   Primary_Device_TV                  9712 non-null   int64
 10  Primary_Device_Tablet              9712 non-null   int64
 11  Urban_or_Rural_Rural               9712 non-null   int64
 12  Urban_or_Rural_Urban               9712 non-null   int64
 13  Health_freq                        9712 non-null   int64
dtypes: int64(13), object(1)
memory usage: 1.0+ MB

In [25]:
df=df.drop('Health_Impacts', axis=1)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   int64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   int64
 2   Exceeded_Recommended_Limit         9712 non-null   int64
 3   Educational_to_Recreational_Ratio  9712 non-null   int64
 4   Gender_Female                      9712 non-null   int64
 5   Gender_Male                        9712 non-null   int64
 6   Primary_Device_Laptop              9712 non-null   int64
 7   Primary_Device_Smartphone          9712 non-null   int64
 8   Primary_Device_TV                  9712 non-null   int64
 9   Primary_Device_Tablet              9712 non-null   int64
 10  Urban_or_Rural_Rural               9712 non-null   int64
 11  Urban_or_Rural_Urban               9712 non-null   int64
 12  Health_freq                        9712 non-null   int64
dtypes: int64(13)
memory usage: 986.5 KB

# Scaling qilish

In [28]:
df.head()

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Gender_Female,Gender_Male,Primary_Device_Laptop,Primary_Device_Smartphone,Primary_Device_TV,Primary_Device_Tablet,Urban_or_Rural_Rural,Urban_or_Rural_Urban,Health_freq
0,6,380,1,12,0,1,0,1,0,0,0,1,979
1,3,442,1,0,1,0,1,0,0,0,0,1,5486
2,10,354,1,2,1,0,0,0,1,0,0,1,5486
3,7,105,0,9,1,0,1,0,0,0,0,1,5486
4,4,570,1,19,1,0,0,1,0,0,0,1,608

In [27]:
num_col=df.columns

In [47]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
standart=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [49]:
df[num_col]=minmax.fit_transform(df[num_col])

In [61]:
df.head(25)

,Age,Avg_Daily_Screen_Time_hr,Exceeded_Recommended_Limit,Educational_to_Recreational_Ratio,Gender_Female,Gender_Male,Primary_Device_Laptop,Primary_Device_Smartphone,Primary_Device_TV,Primary_Device_Tablet,Urban_or_Rural_Rural,Urban_or_Rural_Urban,Health_freq
0,0.6,0.423163,1.0,0.400000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.173179
1,0.3,0.492205,1.0,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.000000
2,1.0,0.394209,1.0,0.066667,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000
3,0.7,0.116927,0.0,0.300000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.000000
4,0.4,0.634744,1.0,0.633333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.105118
5,0.6,0.522272,1.0,0.466667,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.000000
6,0.9,0.309577,0.0,0.600000,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.000000
7,0.2,0.283964,1.0,0.800000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000
8,0.6,0.492205,1.0,0.200000,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.105118
9,1.0,0.339644,1.0,0.600000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.076500
10,1.0,0.371938,1.0,0.466667,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.000000
11,0.7,0.528953,1.0,0.200000,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.000000
12,0.4,0.489978,1.0,0.433333,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.000000
13,0.3,0.655902,1.0,0.600000,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.111723
14,0.7,0.663697,1.0,0.333333,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.000000
15,0.7,0.389755,1.0,0.133333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.000000
16,0.2,0.769488,1.0,0.433333,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.173179
17,0.5,0.756125,1.0,0.600000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.039809
18,0.4,0.404232,1.0,0.333333,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.064208
19,0.1,0.000000,0.0,0.400000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.000000
20,0.7,0.407572,1.0,0.633333,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.039809
21,0.5,0.429844,1.0,0.100000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.111723
22,0.1,0.160356,0.0,0.933333,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.000000
23,0.4,0.733853,1.0,0.100000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.111723
24,0.0,0.334076,1.0,0.800000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.007888

# Model training

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                9712 non-null   float64
 1   Avg_Daily_Screen_Time_hr           9712 non-null   float64
 2   Exceeded_Recommended_Limit         9712 non-null   float64
 3   Educational_to_Recreational_Ratio  9712 non-null   float64
 4   Gender_Female                      9712 non-null   float64
 5   Gender_Male                        9712 non-null   float64
 6   Primary_Device_Laptop              9712 non-null   float64
 7   Primary_Device_Smartphone          9712 non-null   float64
 8   Primary_Device_TV                  9712 non-null   float64
 9   Primary_Device_Tablet              9712 non-null   float64
 10  Urban_or_Rural_Rural               9712 non-null   float64
 11  Urban_or_Rural_Urban               9712 non-null   float64
 12  Health_freq                        9712 non-null   float64
dtypes: float64(13)
memory usage: 986.5 KB

In [66]:
# Input va output qiymatlarga ajratish
X = df.drop('Health_freq', axis=1)          # input qiymatli ustunlar
y = df['Health_freq']                # output (target)

In [ ]:

from sklearn.model_selection import train_test_split

In [64]:
# 4. Train/testga bo‘lish (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [69]:
# 5. Modelni tanlash va o‘qitish
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [72]:
from sklearn.metrics import accuracy_score

In [73]:
# Test ma'lumotlarida bashorat qilish
y_pred = model.predict(X_test)

# Accuracy (aniqlik) ni hisoblash
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy (Health Impact Prediction):", round(accuracy * 100, 2), "%")

Model Accuracy (Health Impact Prediction): 97.07 %