# Data preprocessing

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('blood_donor_dataset.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   donor_id                     9973 non-null   object
 1   name                         9997 non-null   object
 2   email                        9986 non-null   object
 3   password                     9998 non-null   object
 4   contact_number               9988 non-null   object
 5   city                         9975 non-null   object
 6   blood_group                  9984 non-null   object
 7   availability                 10000 non-null  object
 8   months_since_first_donation  9937 non-null   float64
 9   number_of_donation           10000 non-null  int64
 10  pints_donated                10000 non-null  int64
 11  created_at                   10000 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 937.6+ KB

In [4]:
df.isnull().sum()

donor_id                       27
name                            3
email                          14
password                        2
contact_number                 12
city                           25
blood_group                    16
availability                    0
months_since_first_donation    63
number_of_donation              0
pints_donated                   0
created_at                      0
dtype: int64

# Missing qiymatlarni to'ldirish

In [5]:
for col in df.columns:
    if df[col].isnull().sum()<4:
        df.dropna(subset=[col], inplace=True)
    elif df[col].isnull().sum()>9000:
        df.drop(columns=[col], axis=1, inplace=True)
    elif df[col].dtype=="float64":
        df[col].fillna(df[col].mean(),inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\aaa\AppData\Local\Temp\ipykernel_36312\772755720.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_36312\772755720.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_36312\772755720.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_36312\772755720.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   donor_id                     9997 non-null   object
 1   name                         9997 non-null   object
 2   email                        9997 non-null   object
 3   password                     9997 non-null   object
 4   contact_number               9997 non-null   object
 5   city                         9997 non-null   object
 6   blood_group                  9997 non-null   object
 7   availability                 9997 non-null   object
 8   months_since_first_donation  9997 non-null   float64
 9   number_of_donation           9997 non-null   int64
 10  pints_donated                9997 non-null   int64
 11  created_at                   9997 non-null   int64
dtypes: float64(1), int64(3), object(8)
memory usage: 1015.3+ KB

In [7]:
df.head()

,donor_id,name,email,password,contact_number,city,blood_group,availability,months_since_first_donation,number_of_donation,pints_donated,created_at
0,1b8b4c828a,Norma Fisher,ysullivan@yahoo.com,P5hX6Syg*A,+61 461706749,Hobart,A+,No,65.0,31,62,42811
1,a6a3f7fe55,Eugene Bowman,hramos@brown-sellers.com,b6Wq6Cqz@5,+61 450709944,Darwin,AB-,Yes,64.0,8,16,42685
2,cee6478144,Sheri Bolton DDS,jasmine85@hotmail.com,$9RB51m#s7,+61 428756361,Melbourne,AB+,Yes,39.0,6,6,44617
3,5986bc55f9,Kelly Boyd,pattylawrence@riley-hayes.com,@5Tdg(4kCm,+61 454318320,Darwin,A-,No,55.0,20,20,45751
4,93246afe6c,Taylor Guzman,martinezjacob@wilson.com,x!)9Ag@J*7,+61 484158472,Darwin,O-,No,7.0,35,35,44895

# Encoding qilish

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [9]:
for col in df.columns:
    if col == 'availability':
        continue
    if df[col].dtype == 'object': 
        if df[col].nunique()<=5:
            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])
            df['availability'] = encoder.fit_transform(df['availability'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   donor_id                     9997 non-null   int64
 1   name                         9997 non-null   int64
 2   email                        9997 non-null   int64
 3   password                     9997 non-null   int64
 4   contact_number               9997 non-null   int64
 5   city                         9997 non-null   int64
 6   blood_group                  9997 non-null   int64
 7   availability                 9997 non-null   int64
 8   months_since_first_donation  9997 non-null   float64
 9   number_of_donation           9997 non-null   int64
 10  pints_donated                9997 non-null   int64
 11  created_at                   9997 non-null   int64
dtypes: float64(1), int64(11)
memory usage: 1015.3 KB

In [11]:
df.head()

,donor_id,name,email,password,contact_number,city,blood_group,availability,months_since_first_donation,number_of_donation,pints_donated,created_at
0,1079,7073,9813,6072,5806,4,0,0,65.0,31,62,42811
1,6544,3070,3549,7858,4550,3,3,1,64.0,8,16,42685
2,8107,8231,3888,855,2084,5,2,1,39.0,6,6,44617
3,3489,5119,6895,4594,4969,3,1,0,55.0,20,20,45751
4,5753,8641,5659,9744,8266,3,7,0,7.0,35,35,44895

# Scaling qilish

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
minmax=MinMaxScaler()
standard=StandardScaler()
robust=RobustScaler()

In [13]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('availability')

In [14]:
df[num_col]=minmax.fit_transform(df[num_col])

In [15]:
df.head()

,donor_id,name,email,password,contact_number,city,blood_group,availability,months_since_first_donation,number_of_donation,pints_donated,created_at
0,0.108225,0.751248,0.987422,0.607443,0.581530,0.571429,0.000000,0,0.541667,0.62,0.62,0.171139
1,0.656369,0.326075,0.357114,0.786114,0.455729,0.428571,0.428571,1,0.533333,0.16,0.16,0.136637
2,0.813139,0.874243,0.391226,0.085534,0.208734,0.714286,0.285714,1,0.325000,0.12,0.06,0.665663
3,0.349950,0.543707,0.693802,0.459584,0.497696,0.428571,0.142857,0,0.458333,0.40,0.20,0.976177
4,0.577031,0.917791,0.569430,0.974790,0.827925,0.428571,1.000000,0,0.058333,0.70,0.35,0.741785

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9997 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   donor_id                     9997 non-null   float64
 1   name                         9997 non-null   float64
 2   email                        9997 non-null   float64
 3   password                     9997 non-null   float64
 4   contact_number               9997 non-null   float64
 5   city                         9997 non-null   float64
 6   blood_group                  9997 non-null   float64
 7   availability                 9997 non-null   int64
 8   months_since_first_donation  9997 non-null   float64
 9   number_of_donation           9997 non-null   float64
 10  pints_donated                9997 non-null   float64
 11  created_at                   9997 non-null   float64
dtypes: float64(11), int64(1)
memory usage: 1015.3 KB

# Model training

In [17]:
y=df['availability']   #output qiymati

In [18]:
x=df.drop('availability',axis=1)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
x_train.shape

(7997, 11)

In [22]:
x_test.shape

(2000, 11)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
lr=LogisticRegression()

In [25]:
lr

LogisticRegression()

In [26]:
lr.fit(x_train,y_train)

LogisticRegression()