# 3-dars uchun 3-dataset

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('football injury.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         800 non-null    int64
 1   Height_cm                   799 non-null    float64
 2   Weight_kg                   799 non-null    float64
 3   Position                    799 non-null    object
 4   Training_Hours_Per_Week     798 non-null    float64
 5   Matches_Played_Past_Season  799 non-null    float64
 6   Previous_Injury_Count       799 non-null    float64
 7   Knee_Strength_Score         797 non-null    float64
 8   Hamstring_Flexibility       519 non-null    float64
 9   Reaction_Time_ms            745 non-null    float64
 10  Balance_Test_Score          793 non-null    float64
 11  Sprint_Speed_10m_s          788 non-null    float64
 12  Agility_Score               795 non-null    float64
 13  Sleep_Hours_Per_Night       785 non-null    float64
 14  Stress_Level_Score          795 non-null    float64
 15  Nutrition_Quality_Score     797 non-null    float64
 16  Warmup_Routine_Adherence    800 non-null    int64
 17  Injury_Next_Season          800 non-null    int64
 18  BMI                         800 non-null    float64
dtypes: float64(15), int64(3), object(1)
memory usage: 118.9+ KB

In [4]:
df.isnull().sum()

Age                             0
Height_cm                       1
Weight_kg                       1
Position                        1
Training_Hours_Per_Week         2
Matches_Played_Past_Season      1
Previous_Injury_Count           1
Knee_Strength_Score             3
Hamstring_Flexibility         281
Reaction_Time_ms               55
Balance_Test_Score              7
Sprint_Speed_10m_s             12
Agility_Score                   5
Sleep_Hours_Per_Night          15
Stress_Level_Score              5
Nutrition_Quality_Score         3
Warmup_Routine_Adherence        0
Injury_Next_Season              0
BMI                             0
dtype: int64

In [5]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].isnull().any():
            df[col].fillna(df[col].mode()[0],inplace=True)
    else:
        df[col].fillna(df[col].mean(),inplace=True)

C:\Users\aaa\AppData\Local\Temp\ipykernel_16368\2474206149.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\aaa\AppData\Local\Temp\ipykernel_16368\2474206149.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         800 non-null    int64
 1   Height_cm                   800 non-null    float64
 2   Weight_kg                   800 non-null    float64
 3   Position                    800 non-null    object
 4   Training_Hours_Per_Week     800 non-null    float64
 5   Matches_Played_Past_Season  800 non-null    float64
 6   Previous_Injury_Count       800 non-null    float64
 7   Knee_Strength_Score         800 non-null    float64
 8   Hamstring_Flexibility       800 non-null    float64
 9   Reaction_Time_ms            800 non-null    float64
 10  Balance_Test_Score          800 non-null    float64
 11  Sprint_Speed_10m_s          800 non-null    float64
 12  Agility_Score               800 non-null    float64
 13  Sleep_Hours_Per_Night       800 non-null    float64
 14  Stress_Level_Score          800 non-null    float64
 15  Nutrition_Quality_Score     800 non-null    float64
 16  Warmup_Routine_Adherence    800 non-null    int64
 17  Injury_Next_Season          800 non-null    int64
 18  BMI                         800 non-null    float64
dtypes: float64(15), int64(3), object(1)
memory usage: 118.9+ KB

# Encoding

In [7]:
df['Position'].value_counts()

Position
Midfielder    214
Defender      203
Forward       197
Goalkeeper    186
Name: count, dtype: int64

In [8]:
# dummies=pd.get_dummies(df['Position'],prefix='Edit', dtype=int)
# df=pd.concat([df.drop(columns=['Position']),dummies],axis=1)
from sklearn.preprocessing import LabelEncoder

In [9]:
encoder=LabelEncoder()
df['Position_new']=encoder.fit_transform(df['Position'])
df.drop('Position', axis=1, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         800 non-null    int64
 1   Height_cm                   800 non-null    float64
 2   Weight_kg                   800 non-null    float64
 3   Training_Hours_Per_Week     800 non-null    float64
 4   Matches_Played_Past_Season  800 non-null    float64
 5   Previous_Injury_Count       800 non-null    float64
 6   Knee_Strength_Score         800 non-null    float64
 7   Hamstring_Flexibility       800 non-null    float64
 8   Reaction_Time_ms            800 non-null    float64
 9   Balance_Test_Score          800 non-null    float64
 10  Sprint_Speed_10m_s          800 non-null    float64
 11  Agility_Score               800 non-null    float64
 12  Sleep_Hours_Per_Night       800 non-null    float64
 13  Stress_Level_Score          800 non-null    float64
 14  Nutrition_Quality_Score     800 non-null    float64
 15  Warmup_Routine_Adherence    800 non-null    int64
 16  Injury_Next_Season          800 non-null    int64
 17  BMI                         800 non-null    float64
 18  Position_new                800 non-null    int64
dtypes: float64(15), int64(4)
memory usage: 118.9 KB

In [11]:
df['Position_new']

0      3
1      3
2      1
3      0
4      3
      ..
795    2
796    0
797    2
798    2
799    3
Name: Position_new, Length: 800, dtype: int64

# Scaling

In [12]:
df.head(20)

,Age,Height_cm,Weight_kg,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI,Position_new
0,22,173.0,64.0,11.575308,36.0,1.0,77.460279,79.115738,284.487853,91.212476,5.874630,77.599705,8.238293,46.616415,81.472206,1,0,21.383942,3
1,18,170.0,67.0,12.275869,37.0,2.0,72.634442,82.541688,250.579249,87.294078,5.796269,94.418987,8.983737,49.368037,81.056677,1,0,23.183391,3
2,22,186.0,75.0,12.254896,12.0,2.0,77.064490,75.943631,269.119918,83.440688,5.731209,70.179176,7.229193,43.132808,64.877457,0,1,21.678807,1
3,20,172.0,62.0,9.006678,11.0,1.0,82.810232,73.878324,249.375795,87.591894,6.220212,83.473824,7.681029,51.528529,89.824744,1,0,20.957274,0
4,18,172.0,94.0,12.683668,10.0,2.0,76.772859,76.653043,249.375795,83.125161,5.385958,87.037256,6.728091,52.379718,71.569197,0,1,31.773932,3
5,23,189.0,89.0,10.262987,31.0,2.0,78.450720,80.927984,249.375795,81.106339,6.354870,86.418954,8.538027,39.929697,74.982476,1,0,24.915316,2
6,22,189.0,71.0,8.069288,5.0,4.0,63.045009,75.032030,249.375795,76.787369,6.458297,65.179995,7.339327,75.039112,65.790192,0,1,19.876263,3
7,23,184.0,75.0,6.407939,26.0,0.0,77.566677,76.947213,249.375795,93.317382,6.161460,79.260417,8.072895,25.783371,89.782578,0,0,22.152646,2
8,22,174.0,71.0,10.554930,23.0,0.0,78.877905,89.584501,249.375795,80.898575,6.199281,77.152290,7.661190,52.581600,78.587201,1,0,23.450918,3
9,23,185.0,76.0,11.899732,22.0,0.0,83.194761,82.244364,249.375795,89.077577,6.206694,90.396480,6.035505,55.049722,83.947949,1,0,22.205990,3
10,18,178.0,62.0,7.884849,29.0,4.0,78.714830,74.726306,249.375795,74.261622,6.074620,80.813247,8.287460,77.728853,63.488951,1,1,19.568236,1
11,19,188.0,81.0,11.132568,16.0,1.0,67.936758,76.301273,249.375795,74.462333,5.661078,74.857101,6.518113,60.335046,59.963239,0,1,22.917610,0
12,18,183.0,72.0,13.344094,12.0,2.0,79.477855,80.691881,249.375795,88.796646,6.133046,79.846486,7.527362,43.653777,75.520238,1,0,21.499597,3
13,19,198.0,75.0,10.026712,28.0,2.0,72.172303,75.804658,249.375795,82.108525,5.947923,71.881054,6.452557,46.226068,88.220704,1,1,19.130701,0
14,21,181.0,82.0,10.697365,20.0,1.0,74.311420,69.513527,249.375795,79.782254,6.189133,83.618914,7.884363,47.493992,77.838180,1,1,25.029761,0
15,18,174.0,69.0,13.422844,36.0,2.0,66.709014,78.570402,249.375795,65.586739,6.165619,76.818887,5.882157,33.381323,66.087769,0,1,22.790329,3
16,18,168.0,75.0,12.156390,30.0,1.0,69.299743,86.759012,249.375795,83.909148,5.980935,78.751625,7.734276,55.377512,69.060858,0,1,26.573129,2
17,20,162.0,60.0,12.789198,25.0,1.0,66.734752,78.781087,249.375795,78.083770,6.245307,83.659735,7.300053,54.651794,65.700243,1,1,22.862369,0
18,20,169.0,60.0,9.897575,23.0,1.0,76.266892,75.758771,249.375795,84.687991,6.048251,69.153117,8.493185,62.317567,79.764972,1,0,21.007668,2
19,22,164.0,60.0,9.668781,26.0,0.0,81.084702,72.186632,249.375795,84.697161,6.344785,76.845292,7.313220,49.673913,85.917363,1,0,22.308150,3

In [13]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
minmax=MinMaxScaler()
standard=StandardScaler()
robust=RobustScaler()

In [14]:
num_col=df.columns.drop('Injury_Next_Season','Warmup_Routine_Adherence')
df[num_col]=minmax.fit_transform(df[num_col])

In [15]:
df.head()

,Age,Height_cm,Weight_kg,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI,Position_new
0,0.666667,0.413043,0.316667,0.474183,0.911765,0.125,0.603944,0.506726,0.824486,0.779985,0.497199,0.551994,0.666240,0.382500,0.629444,1.0,0,0.321116,1.000000
1,0.000000,0.347826,0.366667,0.524704,0.941176,0.250,0.487683,0.589649,0.556922,0.681879,0.458708,0.888380,0.819606,0.424507,0.621134,1.0,0,0.403222,1.000000
2,0.666667,0.695652,0.500000,0.523192,0.205882,0.250,0.594409,0.429947,0.703222,0.585401,0.426749,0.403584,0.458629,0.329319,0.297549,0.0,1,0.334570,0.333333
3,0.333333,0.391304,0.283333,0.288944,0.176471,0.125,0.732831,0.379958,0.547426,0.689335,0.666952,0.669476,0.551589,0.457490,0.796495,1.0,0,0.301648,0.000000
4,0.000000,0.391304,0.816667,0.554113,0.147059,0.250,0.587383,0.447118,0.547426,0.577501,0.257159,0.740745,0.355534,0.470484,0.431384,0.0,1,0.795196,1.000000

# Model training

In [16]:
y=df['Injury_Next_Season']

In [17]:
x=df.drop('Injury_Next_Season',axis=1)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [20]:
x_train.shape

(640, 18)

In [21]:
x_test.shape

(160, 18)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
lr=LogisticRegression()

In [24]:
lr

LogisticRegression()

In [25]:
lr.fit(x_test,y_test)

LogisticRegression()